---
galaxy_info:
  author: ferrarimarco
  description: Ansible role to install and configure Nano
  license: "license (Apache 2.0)"
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - yakkety
  galaxy_tags:
    - editor
    - nano
